### ISSUE TITLE
Hovering over cards image behind overlay

### ISSUE THREAD

**Issue by notandigg** [StartBootstrap/pro-feedback#1] opened 2020-02-19 12:04 UTC
Hi, I like the new UIkit, well done with that. 
I noticed that when you hover over card in the grid the overlay is over with border-radius applied but the image removes the border-radius
![Screenshot 2020-02-19 at 11 52 29](https://user-images.githubusercontent.com/4629058/74832731-d3b9b780-530f-11ea-93ae-8192a6a57712.png)

**Comment by davidtmiller** [comment] 2020-04-20 20:09
It looks like there needs to be an `overflow: hidden;` rule somewhere in there. I will investigate this further and we'll likely push out a change in the next update to SB UI Kit Pro.

**Comment by davidtmiller** [comment] 2020-11-06 19:18
Looking into this more, it looks like the issue is coming from using box shadow and border radius with cards within a card column. A way to get by this is by not using the card column component from Bootstrap.

I am starting to experiment with ways to get the border radius and box shadow of cards within card columns to work properly by manipulating the padding of the elements within the component.

I've worked this issue into our next release for SB Admin Pro, and our next release for SB UI Kit Pro.

**Comment by davidtmiller** [comment] 2021-05-21 20:08
Closing this since the issue has been fixed with the most recent build of SB UI Kit Pro. The masonry portfolio styling has been simplified a bit to remove this specific animation type. It was not playing well on Safari, so the new animation is better cross browser. We will explore new options for more animation styling moving forward!

**Closed by davidtmiller** 2021-05-21 20:08 UTC
Labels: SB UI Kit Pro, bug, fixed
