### ISSUE TITLE
Utility Animation not working in Edge

### ISSUE THREAD

**Issue by developeregrem** [StartBootstrap/pro-feedback#7] opened 2020-04-05 15:40 UTC
Hi,
first of all you did a great job with the UI Kit Pro. I really like it.

I figured out, that the animation classes did not work in latest Edge Browser. You can see it in your example page her: https://themes.startbootstrap.com/sb-ui-kit-pro/index.html in the nav dropdown.
The dropdown content is not shown when clicking on the link.
When removing the css class animated--fade-in-up it's working.

**Comment by davidtmiller** [comment] 2020-04-20 20:04
We will do some more testing in Edge. It looks like this might be an issue with autoprefixer not compiling some cross browser functionality rules and selectors into the CSS.

**Comment by davidtmiller** [comment] 2020-11-06 19:16
Looking into this for our v1.2.1 release of SB UI Kit Pro and SB Admin Pro.

**Comment by davidtmiller** [comment] 2021-05-21 20:14
Animation utilities are now working as intended in v2 on Edge v90.0.818.62. Closing this one!

**Closed by davidtmiller** 2021-05-21 20:14 UTC
Labels: SB UI Kit Pro, bug, fixed
